# Generated by Django 3.2.7 on 2021-09-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phonenum',
            field=models.IntegerField(null=True),
        ),
    ]
